### PR TITLE
Merge dev to form v3.0.0 release

### PR DESCRIPTION
**Pull request by tomasholderness**
- fixed jshint errors
- improved README
- added license
- added changelog

@matthewberryman this is my proposal to tag a v3.0.0 release, identifying the code that was initially deployed for the 2017 monsoon season in Indonesia. Future additions (e.g. Zurich) can come under point releases. I'd be grateful if you could look over these changes (in particular removal of unused variables) and confirm you're happy to merge to master, and then one of us can tag a release.

### CODE REVIEW

**Comment by matthewberryman** [comment]
@talltom I will review then deploy to our dev environment and then test in dev and then merge after that, bearing in mind short-medium term weather, and then test on master.

**Comment by tomasholderness** [comment]
@matthewberryman Great. Probably already deployed on dev, no?

**Comment by matthewberryman** [comment]
@talltom yes already on dev as it's dev branch we're talking about (sorry was in a bit of a rush when I wrote that yesterday). Anyway, will review and test and merge later today. Do you want DOIs? Easier if I set that up before releasing.

**Comment by matthewberryman** [comment]
@talltom Reviewed and tested and merged; I will test once it's deployed.

**Comment by tomasholderness** [comment]
yes please setup DOIs and I can double check with the team for release of v3.0.0

**Pull request merged**
